$(document).ready(function() {
	
	//original scripts 
	function hide(id) {
	  var el = document.getElementById(id);
	  if (el) { el.style.visibility = 'hidden'; }
	}
	function vote(node) {
	  var v = node.id.split(/_/);
	  var item = v[1];
	  hide('up_'   + item);
	  hide('down_' + item);
	  var ping = new Image();
	  ping.src = node.href;
	  return false;
	}

	//infinite scroll
	var timeOut = null;
	$(window).scroll(function() {
		if ($(window).scrollTop() == $(document).height() - $(window).height() && timeOut === null) {
			$('.morespace, .more').fadeOut();
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 1.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 2.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 3.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 4.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 5.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 6.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 7.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 8.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 9.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			$('.articles').append('<tr class="athing"><td align="right" valign="top" class="title"><span class="rank">+ 10.</span></td><td valjign="top" class="votelinks"><center><a id="up_11224982" href="vote?for=11224982&amp;dir=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><span class="deadmark"></span><a href="#">Another article</a><span class="sitebit comhead"> (<a href="#"><span class="sitestr">link</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="score" id="score_11224982">x points</span> by <a href="#">someone</a> <span class="age"><a href="#">x hours ago</a></span>  | <a href="#">x comments</a></td></tr><tr class="spacer" style="height:5px"></tr>');
			timeOut = setTimeout(function(){ timeOut = null; }, 500);//para não ir somando movimentos da roda do rato, tem de se limpar o timeout quando o scroll chega ao fim da página
		}
	});

})